### PR TITLE
update ci

### PR DESCRIPTION
**Pull request by faddat**
This updates ci:

* go 1.20
* use ghcr.io for docker images

### CODE REVIEW

**Comment by anhductn2001** [comment]
I just push a commit to change tag of image, hope it works @faddat

**Comment by anhductn2001** [comment]
If you can, please publish this image, like the pain in Whitewhale 
https://github.com/osmosis-labs/fee-abstraction/pkgs/container/fee-abstraction-ictest

**Comment by anhductn2001** [comment]
Hey @faddat, As discussed with @niccoloraspa  we will only use Docker Hub to store image of Osmosis.

**Comment by faddat** [comment]
@anhductn2001 that's how he'd like it because it is in the osmosis org, or is it something else?

If that's how he'd like it, please close this pr. 

<3

**Comment by anhductn2001** [comment]
yea. I think maybe he and the team are used to working with DockerHub, they are essentially the same, now I will close PR. Thankss

**Comment by faddat** [comment]
Actually it looks like we still need the other changes here, so I am going to merge this and thank you very much

**Pull request merged**
