### PR TITLE
update declarations to point to Osmosis

### PR DESCRIPTION
**Pull request by vuong177**
Closes: #7 

Update declarations to point to Osmosis : github.com/osmosis-labs/fee-abstraction/v2

### CODE REVIEW

**Review by daniel-farina — APPROVED** [review]
lgtm! thanks!

**Comment by daniel-farina** [comment]
It looks like tests are failing pointing to notional:

```
ERROR: failed to solve: failed to push ghcr.io/notional-labs/fee-abstraction-ictest:latest: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/notional-labs/fee-abstraction-ictest:latest: unexpected status: 403 Forbidden
```

**Comment by vuong177** [comment]
@daniel-farina  we need to move ghrc to the osmosis repo cc @anhductn2001

**Review by daniel-farina — APPROVED** [review]
lgtm

**Comment by faddat** [comment]
ok, looks like this is set, except for interchain test.  merging it **might** fix interchain test (so that building the docker container can work)

**Comment by faddat** [comment]
Few other erratta related to interchain test I've got ot fix, b ut this'll work and get us moving much faster

**Pull request merged**
