### PR TITLE
Fix: Fix workflow to run all interchaintest tests as expected

### PR DESCRIPTION
**Pull request by tropicaldog**
## Changes

 + Fix running wrong test in Makefile:

  Currently `make ictest-feeabs` and `make ictest-ibc` are running the same `TestFeeabsGaiaIBCTransfer`, and the `TestFeeAbs` in feeabs_test.go is ignored because it doesn't start with `TestFeeabs`, which cause misleading tests success.
Now run the `TestFeeAbs` by exact match to save time, not sure if `make ictest-feeabs` is intended to run both the `TestFeeabsGaiaIBCTransfer` and the `TestFeeAbs`. 

+ Fix using correct code id when instantiate contract instead of bytecode path.
 
After running the TestFeeAbs, an error occur related to contract instantiation. Fixed by using correct code id when instantiate contract.

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
I also detect missing check for feeabs check in TestQueryOsmosisTwap, result from querying feeabs is not checked: https://github.com/osmosis-labs/fee-abstraction/blob/main/tests/interchaintest/query_osmosis_twap_test.go#L115

**Comment by nghuyenthevinh2000** [comment]
This is the error when executing feeabs wasm msg

Screenshot 2024-03-23 at 02 27 10

**Comment by tropicaldog** [comment]
> This is the error when executing feeabs wasm msg
> 
> Screenshot 2024-03-23 at 02 27 10

I think the channel id should be registered in the register contract first.

**Comment by nghuyenthevinh2000** [comment]
> > This is the error when executing feeabs wasm msg
> > Screenshot 2024-03-23 at 02 27 10
> 
> I think the channel id should be registered in the registry contract first.

it is gas problem, I have fixed that one

**Review by nghuyenthevinh2000 — APPROVED** [review]

**Pull request merged**
