### PR TITLE
update docker images

### PR DESCRIPTION
**Pull request by faddat**
this is an attempt to possibly resolve the flaky test

- update docker images
- update buf

### CODE REVIEW

**Comment by anhductn2001** [comment]
Have you tried test build it? and try generate proto?

**Comment by faddat** [comment]
Not yet.  Actually to think of it, what we should do is push this to the same docker org we are pushing the other images to.

**Comment by faddat** [comment]
Can you handle getting that push set up?  And make the job run only when that Dockerfile is changed?

**Comment by anhductn2001** [comment]
Yes, I will handle this.

**Comment by faddat** [comment]
@expertdicer -- please note that at first, the .proto files may fail to build.  If they do, please call me on Signal -- we just need to put them in fully qualified paths

**Comment by anhductn2001** [comment]
> Can you handle getting that push set up? And make the job run only when that Dockerfile is changed?

It be merged at #68

**Pull request closed without merging**
