### PR TITLE
Add min swap amount to each host zone config for improve cross chain swap call

### LINKED ISSUE #155: Improve crosschain swap call
In the current implementation, cross swap is called each end of epoch. It's ineffective when amount of token maybe very small.

Need add a field `MinSwapAmount` on each `HostZoneConfig`, cross swap should be called when bypass `MinSwapAmount` value.

### PR DESCRIPTION
**Pull request by tnv1**
Closed #155.

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
Please provide relevant tests for logic

**Comment by tropicaldog** [comment]
I wonder why we have two instances of `HostChainFeeAbsConfig` in both [interchaintest](https://github.com/osmosis-labs/fee-abstraction/blob/main/tests/interchaintest/feeabs/types.go#L17) and [x/feeabs](https://github.com/osmosis-labs/fee-abstraction/blob/main/x/feeabs/types/proposal.pb.go#L56) package? What is the context behind this? @tnv1 @nghuyenthevinh2000

**Comment by nghuyenthevinh2000** [comment]
> I wonder why we have two instances of `HostChainFeeAbsConfig` in both [interchaintest](https://github.com/osmosis-labs/fee-abstraction/blob/main/tests/interchaintest/feeabs/types.go#L17) and [x/feeabs](https://github.com/osmosis-labs/fee-abstraction/blob/main/x/feeabs/types/proposal.pb.go#L56) package? What is the context behind this? @tnv1 @nghuyenthevinh2000 

That is due to json unmarshall structure, field pool id in feeabs is uint, which json string cannot be unmarshaled into, thus needed a string field

**Review by tropicaldog — APPROVED** [review]

**Comment by nghuyenthevinh2000** [comment]
@tropicaldog you forgot to add a success case

**Pull request merged**
